import { Link } from 'react-router-dom'

const EFFECTIVE = 'June 28, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <Link to="/login" className="text-indigo-400 hover:text-indigo-300 text-sm transition-colors">← Back to login</Link>
          <h1 className="text-3xl font-bold text-white mt-6 mb-1">Terms of Service</h1>
          <p className="text-slate-500 text-sm">Effective {EFFECTIVE} · PolyHQ LLC</p>
        </div>

        <div className="prose-polyhq space-y-8 text-slate-300 text-sm leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-white mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using PolyHQ (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service. These Terms constitute a legally binding agreement between you and <strong className="text-white">PolyHQ LLC</strong>, a limited liability company ("PolyHQ," "we," "us," or "our").</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">2. Description of Service</h2>
            <p>PolyHQ is a payroll and crew management platform designed for small service businesses. Features include employee time tracking, job scheduling, payroll calculation, invoicing, and expense accounting. The Service is provided as software-as-a-service accessible via web browser.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">3. Eligibility</h2>
            <p>You must be at least 18 years old and have the legal authority to enter into these Terms on behalf of yourself or your business. By using the Service, you represent that you meet these requirements.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">4. Your Account</h2>
            <p>You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Notify us immediately at <a href="mailto:support@polyhqapp.com" className="text-indigo-400 hover:text-indigo-300">support@polyhqapp.com</a> if you suspect unauthorized access. We reserve the right to disable accounts that violate these Terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2 text-slate-400">
              <li>Use the Service for any unlawful purpose or in violation of applicable labor, tax, or employment laws</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of the Service</li>
              <li>Transmit any malicious code, spam, or unauthorized advertising</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
              <li>Share your account credentials with unauthorized third parties</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">6. Your Data</h2>
            <p>You retain ownership of all data you input into the Service ("Your Data"). By using the Service, you grant PolyHQ LLC a limited license to store and process Your Data solely to provide the Service to you. We do not sell Your Data to third parties. See our <Link to="/privacy" className="text-indigo-400 hover:text-indigo-300">Privacy Policy</Link> for full details.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">7. Payroll Disclaimer</h2>
            <p>PolyHQ provides payroll estimation tools for informational purposes. Payroll calculations, tax withholdings, and related figures generated by the Service are estimates only and do not constitute tax or legal advice. You are solely responsible for ensuring compliance with all federal, state, and local payroll, tax, and employment laws. We strongly recommend consulting a licensed accountant or payroll professional for final payroll processing.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">8. Intellectual Property</h2>
            <p>The Service, including all software, design, trademarks, and content created by PolyHQ LLC, is owned by PolyHQ LLC and protected by applicable intellectual property laws. Nothing in these Terms grants you a right to use our trademarks, logos, or brand features without our prior written consent.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">9. Disclaimers</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. POLYHQ LLC DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">10. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, POLYHQ LLC AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">11. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless PolyHQ LLC and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including reasonable attorneys' fees) arising from your use of the Service, your violation of these Terms, or your violation of any third-party rights.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">12. Termination</h2>
            <p>We may suspend or terminate your access to the Service at any time with or without cause, with or without notice. Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination (including Sections 8–11) shall survive.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">13. Governing Law</h2>
            <p>These Terms are governed by the laws of the State of Delaware, without regard to its conflict-of-law provisions. Any dispute arising from these Terms shall be resolved exclusively in the state or federal courts located in Delaware, and you consent to personal jurisdiction in those courts.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">14. Changes to These Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on this page with a new effective date. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">15. Contact</h2>
            <p>Questions about these Terms? Contact us at:</p>
            <address className="not-italic mt-2 text-slate-400">
              PolyHQ LLC<br />
              <a href="mailto:support@polyhqapp.com" className="text-indigo-400 hover:text-indigo-300">support@polyhqapp.com</a>
            </address>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-slate-800 flex flex-wrap gap-4 text-xs text-slate-600">
          <span>© 2026 PolyHQ LLC. All rights reserved.</span>
          <Link to="/privacy" className="text-slate-500 hover:text-slate-300 transition-colors">Privacy Policy</Link>
        </div>
      </div>
    </div>
  )
}
